### ISSUE TITLE
Change lib includes from <> to just direct references

### ISSUE THREAD

**Issue by megamorphg** [tdalon/ahk#12]
I put some of the files from your library that I like to use (Teams.ahk) in a generic lib folder stored on my OneDrive for convenience.

When I run a script that needs to use the Teams functions, I declare the following at the top of the script:
```
#Include ..\lib
#Include Teams.ahk
```

However, this fails because the Teams.ahk is referencing other lib files that are next to it as a library using <>
```
#Include <People>
#Include <UriDecode>
#Include <Teamsy>
#Include <Clip>
#Include <FindText>
#Include <UIA_Interface>
```

I have to thus change the Teams.ahk (includes within includes) to do a direct include like:
```
#Include People.ahk
#Include UriDecode.ahk
#Include Teamsy.ahk
#Include Clip.ahk
#Include FindText.ahk
#Include UIA_Interface.ahk
```

This would suck in case of your future updates. Otherwise I have to move the library to the MyDocuments library folder (not-synced) or do symlinks.

Anyway, hopefully you can just change these to direct references, otherwise I am not understanding why it is more valuable to do it this way (I am kind of new).

**Comment by tdalon** [comment]
Hi Ahmed. Thanks for your interest in my libraries/ code.

> However, this fails because the Teams.ahk is referencing other lib files that are next to it as a library using <>

I don't get why you don't put the other files next to the Teams.ahk - all in your Lib folder

**Comment by megamorphg** [comment]
@tdalon I sync your repository to a sub-folder in my library--so that if you make updates I can just update the directory (I haven't need to change your code at all yet).
This keeps things simple for me and also in case your library uses a specific version of another library, etc.

Anyway, changing the includes to be more direct should not have any negative impact to anyone, I think?

**Comment by tdalon** [comment]
Now this is a bit clearer - this info about a subfolder only for my libs was not mentioned in the original post.
I guess it is only an issue because you use other libraries included somewhere else also part of my repo like UIAutomation that you don't want to take from mine.
This is a weird deployment.
Normally you shall take all the files required from my lib folder and put them in your lib folder.
And it shall work without any change needed on my part.

Maybe I still didn't get it and you can describe better your scenario.

**Comment by tdalon** [comment]
> `#Include ..\lib
#Include Teams.ahk`

Why don't you use 
`#Include <Teams>`

instead?

**Comment by megamorphg** [comment]
> I guess it is only an issue because you use other libraries included somewhere else also part of my repo like UIAutomation that you don't want to take from mine.

That is not the case, I use just your library, I just don't want to copy paste yours to any library folders. I'd rather just have github update the repo automatically.

> Normally you shall take all the files required from my lib folder and put them in your lib folder.
Yes this is what I have done, copy pasted to the library folder on the machine:
https://www.autohotkey.com/docs/Functions.htm#lib

But for portability sake I would like to setup something like this and not have to use the machine's library folders.
MyScriptFolder\MyScript.exe
MyScriptFolder\!GitHub\tdalon-office <== auto-synced to GitHub

**Comment by tdalon** [comment]
It is not so easy to change.
Example: Teamsy includes Lib/Teams. If I change in Teams/Lib to #Include People.ahk when compiling I get an error 

Ahk2Exe Error
#include file cannot be opened.

Specifically:
"C:\GitHub\ahk\People.ahk"


C:\GitHub\ahk\ is my main directory. People.ahk is located in Lib subdirectory.
So I won't change because I need to be able to compile.

**Comment by tdalon** [comment]
Not able to implement this improvement because of compile error.
